kotlin.code.style=official
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Default Dependencies
mcVersion=1.21.11
mcVersionRange=[1.21,26.1)
neoVersion=21.11.38-beta
neoVersionRange=[21.0.0,)
parchmentMCVersion=1.21.11
parchmentMappingsVersion=2025.12.20
loaderVersionRange=[1,)

# Dev
env=dev
devVersion=1

# Mod Properties
modId=potion_totems
modName=PotionTotems
modDescription=Still dying after using a totem? Not anymore! \nProtect your death with regeneration! Or with strength! It's all yours...
modGroupId=io.github.scaredsmods.potion_totems
modVersion=2.0.0
modLicense=LGPL-3.0-or-later
modAuthors=ScaredRabbitNL

# Dependencies
resourcefulLibVersion=3.11.0
fzzyConfigVersion=0.7.6+1.21.11
kffVersion=6.1.0
#emiVersion=1.1.22+1.21.11
