kotlin.code.style=official
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Default Dependencies
mcVersion=1.21.1
mcVersionRange=[1.21,1.22)
neoVersion=21.1.113
neoVersionRange=[21.1.113,)
parchmentMCVersion=1.21.1
parchmentMappingsVersion=2024.11.17
loaderVersionRange=[1,)

# Mod Properties
modId=example_mod
modName=Example Mod
modDescription=Example mod description.\nNewline characters can be used and will be replaced properly.
modGroupId=io.github.scaredsmods.examplemod
modVersion=1.0.0
modLicense=MIT
modAuthors=MyName, YourName

# Dependencies

