kotlin.code.style=official
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Default Dependencies
mcVersion=26.1
mcVersionRange=[26, )
neoVersion=26.1.0.15-beta
neoVersionRange=[26.1.0,)
loaderVersionRange=[1,)

# Dev
env=dev
devVersion=2

# Mod Properties
modId=potion_totems
modName=PotionTotems
modDescription=Still dying after using a totem? Not anymore! \nProtect your death with regeneration! Or with strength! It's all yours...
modGroupId=io.github.scaredsmods.potion_totems
modVersion=2.0.0
modLicense=LGPL-3.0-or-later
modAuthors=ScaredRabbitNL

# Dependencies
resourcefulLibVersion=4.0.0
fzzyConfigVersion=0.7.6+26.1
kffVersion=6.1.0

